name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: ['ubuntu-latest', 'windows-latest', 'macOS-latest']

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Instal dependencies
        run: npm install

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: ['ubuntu-latest', 'windows-latest', 'macOS-latest']

    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Instal dependencies
        run: npm install
      - name: Unit test
        run: npm run test --if-present
